language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script: make test
notifications:
  email:
    recipients:
      - jonas_cheng@trend.com.tw
    on_success: always
    on_failure: always
